package TravelAgencyModule.TravelAgencyPackage;


/**
* TravelAgencyModule/TravelAgencyPackage/TripListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Amine/Desktop/M2/tp_corba/src/main/idl/TravelAgency.idl
* Saturday, December 28, 2024 3:51:26 PM WAT
*/

public final class TripListHolder implements org.omg.CORBA.portable.Streamable
{
  public TravelAgencyModule.Trip value[] = null;

  public TripListHolder ()
  {
  }

  public TripListHolder (TravelAgencyModule.Trip[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TravelAgencyModule.TravelAgencyPackage.TripListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TravelAgencyModule.TravelAgencyPackage.TripListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TravelAgencyModule.TravelAgencyPackage.TripListHelper.type ();
  }

}
