package TravelAgencyModule;


/**
* TravelAgencyModule/_TravelAgencyStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Amine/Desktop/M2/tp_corba/src/main/idl/TravelAgency.idl
* Saturday, December 28, 2024 3:51:26 PM WAT
*/

public class _TravelAgencyStub extends org.omg.CORBA.portable.ObjectImpl implements TravelAgencyModule.TravelAgency
{

  public TravelAgencyModule.Trip[] getAvailableTrips ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getAvailableTrips", true);
                $in = _invoke ($out);
                TravelAgencyModule.Trip $result[] = TravelAgencyModule.TravelAgencyPackage.TripListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getAvailableTrips (        );
            } finally {
                _releaseReply ($in);
            }
  } // getAvailableTrips

  public boolean bookTrip (int tripId, String clientName)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("bookTrip", true);
                $out.write_long (tripId);
                $out.write_string (clientName);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return bookTrip (tripId, clientName        );
            } finally {
                _releaseReply ($in);
            }
  } // bookTrip

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:TravelAgencyModule/TravelAgency:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _TravelAgencyStub
