package TravelAgencyModule;


/**
* TravelAgencyModule/TravelAgency.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Amine/Desktop/M2/tp_corba/src/main/idl/TravelAgency.idl
* Saturday, December 28, 2024 3:51:26 PM WAT
*/

public interface TravelAgency extends TravelAgencyOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface TravelAgency
