package TravelAgencyModule;


/**
* TravelAgencyModule/TravelAgencyPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Amine/Desktop/M2/tp_corba/src/main/idl/TravelAgency.idl
* Saturday, December 28, 2024 3:51:26 PM WAT
*/

@SuppressWarnings("unchecked")
public abstract class TravelAgencyPOA extends org.omg.PortableServer.Servant
 implements TravelAgencyModule.TravelAgencyOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  @SuppressWarnings("rawtypes")
  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getAvailableTrips", new java.lang.Integer (0));
    _methods.put ("bookTrip", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // TravelAgencyModule/TravelAgency/getAvailableTrips
       {
         TravelAgencyModule.Trip $result[] = null;
         $result = this.getAvailableTrips ();
         out = $rh.createReply();
         TravelAgencyModule.TravelAgencyPackage.TripListHelper.write (out, $result);
         break;
       }

       case 1:  // TravelAgencyModule/TravelAgency/bookTrip
       {
         int tripId = in.read_long ();
         String clientName = in.read_string ();
         boolean $result = false;
         $result = this.bookTrip (tripId, clientName);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:TravelAgencyModule/TravelAgency:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public TravelAgency _this() 
  {
    return TravelAgencyHelper.narrow(
    super._this_object());
  }

  public TravelAgency _this(org.omg.CORBA.ORB orb) 
  {
    return TravelAgencyHelper.narrow(
    super._this_object(orb));
  }


} // class TravelAgencyPOA
