package TravelAgencyModule;


/**
* TravelAgencyModule/Trip.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Amine/Desktop/M2/tp_corba/src/main/idl/TravelAgency.idl
* Saturday, December 28, 2024 3:51:26 PM WAT
*/

public final class Trip implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String destination = null;
  public double price = (double)0;
  public int availableSeats = (int)0;

  public Trip ()
  {
  } // ctor

  public Trip (int _id, String _destination, double _price, int _availableSeats)
  {
    id = _id;
    destination = _destination;
    price = _price;
    availableSeats = _availableSeats;
  } // ctor

} // class Trip
