package TravelAgencyModule;


/**
* TravelAgencyModule/TripHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Amine/Desktop/M2/tp_corba/src/main/idl/TravelAgency.idl
* Saturday, December 28, 2024 3:51:26 PM WAT
*/

abstract public class TripHelper
{
  private static String  _id = "IDL:TravelAgencyModule/Trip:1.0";

  public static void insert (org.omg.CORBA.Any a, TravelAgencyModule.Trip that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static TravelAgencyModule.Trip extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "id",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "destination",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_double);
          _members0[2] = new org.omg.CORBA.StructMember (
            "price",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[3] = new org.omg.CORBA.StructMember (
            "availableSeats",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (TravelAgencyModule.TripHelper.id (), "Trip", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static TravelAgencyModule.Trip read (org.omg.CORBA.portable.InputStream istream)
  {
    TravelAgencyModule.Trip value = new TravelAgencyModule.Trip ();
    value.id = istream.read_long ();
    value.destination = istream.read_string ();
    value.price = istream.read_double ();
    value.availableSeats = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, TravelAgencyModule.Trip value)
  {
    ostream.write_long (value.id);
    ostream.write_string (value.destination);
    ostream.write_double (value.price);
    ostream.write_long (value.availableSeats);
  }

}
