package TravelAgencyModule.TravelAgencyPackage;


/**
* TravelAgencyModule/TravelAgencyPackage/TripListHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Amine/Desktop/M2/tp_corba/src/main/idl/TravelAgency.idl
* Saturday, December 28, 2024 3:51:26 PM WAT
*/

abstract public class TripListHelper
{
  private static String  _id = "IDL:TravelAgencyModule/TravelAgency/TripList:1.0";

  public static void insert (org.omg.CORBA.Any a, TravelAgencyModule.Trip[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static TravelAgencyModule.Trip[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = TravelAgencyModule.TripHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (TravelAgencyModule.TravelAgencyPackage.TripListHelper.id (), "TripList", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static TravelAgencyModule.Trip[] read (org.omg.CORBA.portable.InputStream istream)
  {
    TravelAgencyModule.Trip value[] = null;
    int _len0 = istream.read_long ();
    value = new TravelAgencyModule.Trip[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = TravelAgencyModule.TripHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, TravelAgencyModule.Trip[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      TravelAgencyModule.TripHelper.write (ostream, value[_i0]);
  }

}
